# Generated by Django 3.1.6 on 2021-02-07 19:28

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_marks_obtained', models.IntegerField(default=0)),
                ('quiz_user_created_at', models.DateField(blank=True, default=datetime.datetime(2021, 2, 7, 19, 28, 38, 420152, tzinfo=utc))),
                ('quiz_object', models.ManyToManyField(to='quiz.quizC')),
                ('quiz_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userQuestionMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_marks_obtained', models.IntegerField(default=0)),
                ('ques_object', models.ManyToManyField(to='question.ques')),
                ('quiz_user_object', models.ManyToManyField(to='portal.userQuiz')),
            ],
        ),
    ]
