# Generated by Django 3.1.6 on 2021-02-07 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0002_auto_20210207_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='userQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_marks_obtained', models.IntegerField()),
                ('quiz_object', models.ManyToManyField(to='quiz.quizC')),
                ('quiz_user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userQuestionMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_marks_obtained', models.IntegerField()),
                ('ques_object', models.ManyToManyField(to='question.ques')),
                ('quiz_user_object', models.ManyToManyField(to='portal.userQuiz')),
            ],
        ),
    ]
