# Generated by Django 3.1.6 on 2021-02-07 19:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='quiz_user_created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 7, 19, 29, 12, 635617, tzinfo=utc)),
        ),
    ]
