# Generated by Django 3.1.6 on 2021-02-07 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0002_auto_20210207_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='quizSubSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_subject_title', models.CharField(max_length=50)),
                ('sub_subjects_questions', models.ManyToManyField(to='question.ques')),
            ],
        ),
        migrations.CreateModel(
            name='quizSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(max_length=50)),
                ('sub_subject_objects', models.ManyToManyField(to='quiz.quizSubSubject')),
            ],
        ),
        migrations.CreateModel(
            name='quizC',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_title', models.CharField(max_length=50)),
                ('quiz_desc', models.CharField(max_length=200)),
                ('quiz_total_marks', models.IntegerField()),
                ('maxTime', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('subjects_objects', models.ManyToManyField(to='quiz.quizSubject')),
            ],
        ),
    ]
