# Generated by Django 3.1.6 on 2021-02-07 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mcq_option',
            fields=[
                ('mcq_option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_desc', models.CharField(max_length=50)),
                ('is_ans', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ques',
            fields=[
                ('ques_id', models.AutoField(primary_key=True, serialize=False)),
                ('ques_title', models.CharField(max_length=50)),
                ('ques_desc', models.CharField(max_length=200)),
                ('ques_type', models.CharField(choices=[('MCQ', 'MCQ'), ('TF', 'TF'), ('IntegerType', 'IntegerType')], default='MCQ', max_length=20)),
                ('ques_marks', models.IntegerField(default=0)),
                ('ques_reason', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf_ans', models.BooleanField(default=False)),
                ('ques_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.ques')),
            ],
        ),
        migrations.CreateModel(
            name='mcq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_options', models.IntegerField(default=0)),
                ('mcq_option_objects', models.ManyToManyField(to='question.mcq_option')),
                ('ques_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.ques')),
            ],
        ),
        migrations.CreateModel(
            name='integerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integerType_ans', models.IntegerField(default=0)),
                ('ques_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.ques')),
            ],
        ),
    ]
