# Generated by Django 3.1.6 on 2021-02-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq',
            name='mcq_option_objects',
        ),
        migrations.AddField(
            model_name='mcq',
            name='mcq_option_objects',
            field=models.ManyToManyField(to='question.mcq_option'),
        ),
    ]
